spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productos
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.security: info
    com.is4tech: info
    com.is4tech.reporting.dynamic: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
